# Generated by Django 2.2.24 on 2022-01-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_auto_20220114_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='time_make',
            field=models.CharField(max_length=1, verbose_name='تاریخ ساخت'),
        ),
    ]
