# Generated by Django 2.2.24 on 2022-01-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_auto_20220114_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='time_make',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ساخت'),
        ),
    ]
