# Generated by Django 4.0.1 on 2022-01-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_auto_20220114_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
