# Generated by Django 3.2.9 on 2021-12-03 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='reg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ارسال پیام'),
            preserve_default=False,
        ),
    ]
