# Generated by Django 3.2.9 on 2021-12-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_auto_20211203_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title1',
            field=models.CharField(default='hichi', max_length=50, verbose_name='تیتر اول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title2',
            field=models.CharField(default='hichi', max_length=50, verbose_name='تیتر دوم'),
            preserve_default=False,
        ),
    ]
